### ISSUE TITLE
Ransomware

### ISSUE THREAD

**Issue by sampy901** [mauricerizat/PNG-Grid-Background-Remover#2]
It has a ransomware Trojan inside it.

**Comment by sampy901** [comment]
Trojan:Win32/CryptInject!ml which is apparently some tech support porn virus ransomware scam

**Comment by mauricerizat** [comment]
Thanks for pointing that out. Not sure how a virus would have gotten there but I'll check it again and fix it.

**Comment by mauricerizat** [comment]
I have checked the repo and there aren't any viruses in it, especially none of the type described. Perhaps this was a false alarm.
